apiVersion: v1
kind: Service
metadata:
  name: test2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: test2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - name: test2
        image: test2
        ports:
        - containerPort: 8080
